#!/bin/bash

# Resolve directory of the script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Run the project
$DIR/gradlew -b $DIR/build.gradle run -q --args="$1 $2 $3 $4"
